### ISSUE TITLE
关于论文中问题定义的疑问

### ISSUE THREAD

**Issue by littttttlebird** [songhaoyu/KvPI#1]
论文中把问题定义为求解F(P, R) -> (e, c, i)的映射关系。但是实际上：
（1）很多情况下单凭R，是不能确定R中所涉及的属性是否是属于说话这自己；
（2）标注人员也是结合Post信息对response信息进行理解，然后判断和profile关系的；
比如：
Post: 同桌的你是双鱼啊？    profile: {'constellation':   '处女座', 'loc': '陕西 西安', 'gender': 'female'}
Response:  就是摩羯啊~我觉得这个星座挺好的
Response Annotated Attributes:  {'constellation':   '摩羯座'}
在这个case中，如果不看Post，很难确定response中“摩羯座”是在说自己。比如把post换成”你弟弟竟然是摩羯座？”，response中的摩羯座就指说话人的弟弟了，而不是指说话人自己。

所以这里建模成F(P, R) -> (e, c, i)，而忽略了post信息，而又使用了基于post的理解下的标注标签，这是不太合理的吧？

**Comment by haoyusoong** [comment]
标注过程为了简化问题、统一标准，没有向标注人员提供post。当遇到response缺少主语的情况，我们让标注人员默认response**主语均为“我”**。数据集提供post是为了数据的完整性。
你说的问题涉及到对话中的省略恢复技术，在该任务中我们特意排除了这一问题。模型在现有的数据上能够学到不同人称回复情况下的一致性分类。

**Comment by chuanhuayang** [comment]
“你说的问题涉及到对话中的省略恢复技术，在该任务中我们特意排除了这一问题。模型在现有的数据上能够学到不同人称回复情况下的一致性分类。”
--------------------------------

**Comment by littttttlebird** [comment]
你说的问题涉及到对话中的省略恢复技术，在该任务中我们特意排除了这一问题。模型在现有的数据上能够学到不同人称回复情况下的一致性分类。
---------------------------------------------
1. “特意排除了这一问题”，指的是"response缺少主语是默认指代自己”是吗？
2. “模型在现有的数据上能够学到不同人称回复情况下的一致性分类”，指的是“如果response包含了完整的主语（你，我，他）,模型是会学到和主语相匹配的分类结果”是吗？

**Comment by haoyusoong** [comment]
1. 对
2. 数据中存在很多类似“可情你是白羊座“、”因为他是女孩子”等二三人称主语的回复

**Comment by littttttlebird** [comment]
OK，理解了，赞！！
