### ISSUE TITLE
标注数据好到令人发指~，我是来点赞的，另外感觉local标的过于严格，还是我对数据构造理解有误？

### ISSUE THREAD

**Issue by jkkl** [songhaoyu/KvPI#3]
能给下train script吗？刚好在落地同样的工作。

**Comment by jkkl** [comment]
感觉对local的标注有些，过于严格，看到一些case，感觉并不能从response看出与设定相矛盾？
![image](https://user-images.githubusercontent.com/3937341/120642581-a9a9eb80-c4a7-11eb-929b-82995dbc5954.png)

**Comment by haoyusoong** [comment]
数据标注由于主观判断的确可能会存在过严的情况，但是标准都是始终一致的。构造过程唯一值得注意的就是在缺少主语时标注人员会认为默认主语为第一人称“我”，即默认数据是在谈论自己

**Comment by haoyusoong** [comment]
> 能给下train script吗？刚好在落地同样的工作。

请发邮件hysong@ir.hit.edu.cn

**Comment by jkkl** [comment]
> > 能给下train script吗？刚好在落地同样的工作。
> 
> 请发邮件[hysong@ir.hit.edu.cn](mailto:hysong@ir.hit.edu.cn)

感谢回复，已发邮件，w.yz98@qq.com，谢谢~

**Comment by haoyusoong** [comment]
请使用机构邮箱发送邮件～
